// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_m7hkR5YX_PS0BeWySN5QsdihjkmyKbY',
    appId: '1:1000430522028:web:8a27ddcfb28e11a507d909',
    messagingSenderId: '1000430522028',
    projectId: 'travelnest-f60d5',
    authDomain: 'travelnest-f60d5.firebaseapp.com',
    storageBucket: 'travelnest-f60d5.appspot.com',
    measurementId: 'G-6YBMFZWWQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9wkCSikaTXj9UGmUZHDcTzjGNrzzZUPw',
    appId: '1:1000430522028:android:2cf72627e01ea55607d909',
    messagingSenderId: '1000430522028',
    projectId: 'travelnest-f60d5',
    storageBucket: 'travelnest-f60d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwyObOGkxs-w89YVPmfU_LE2_ewBoYCU',
    appId: '1:1000430522028:ios:b016a3bacb6a24d907d909',
    messagingSenderId: '1000430522028',
    projectId: 'travelnest-f60d5',
    storageBucket: 'travelnest-f60d5.appspot.com',
    iosBundleId: 'com.example.travelnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwyObOGkxs-w89YVPmfU_LE2_ewBoYCU',
    appId: '1:1000430522028:ios:a7217891b2cf8c1307d909',
    messagingSenderId: '1000430522028',
    projectId: 'travelnest-f60d5',
    storageBucket: 'travelnest-f60d5.appspot.com',
    iosBundleId: 'com.example.travelnest.RunnerTests',
  );
}
